# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3e730ce2fd7e94c94848dbb5eaf32c4d1fa71caf199f9855614952e7b7988960751a3daefdcf11d97688f827acb94db5d0bd813e2d2cd02a05a5dfb361a4489

test:
  secret_key_base: 60722c660753e4e6e51e2c537a4dd30fdbc42f2bcd3987ff6e60e6d9bcc8815c784e0e12131c0d7f0ed5a5a454ab197846ebe65c2b4cced544d2499d49b596e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
